CREATE ROLE "user" LOGIN PASSWORD 'user';
CREATE ROLE admin LOGIN PASSWORD 'admin';

REVOKE ALL ON schema public FROM public;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM public;
REVOKE ALL ON ALL PROCEDURES IN SCHEMA public FROM public;
REVOKE ALL ON ALL ROUTINES IN SCHEMA public FROM public;
-- For Admin
GRANT USAGE ON SCHEMA public TO admin;
GRANT ALL ON SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON DATABASE retail_analitycs TO admin;
GRANT SELECT, INSERT, UPDATE, TRUNCATE, DELETE ON ALL TABLES IN SCHEMA public TO admin;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO admin;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO admin;
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA public TO admin;

-- For User
GRANT USAGE ON SCHEMA public TO "user";
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "user";
-- Предоставление доступа для чтения новых таблиц
-- SET ROLE admin;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "user";
-- RESET ROLE;
-- SELECT current_user, session_user;

